POST /many Solves + test | puzzleType adjustment | minor change for tests
Outreaver/VirsTimer pull request #50
Opened 2021-11-30 17:53 UTC by Javorus

2021-12-03 18:29 UTC, akmieckowiak requested changes

2021-12-03 18:29 UTC, akmieckowiak commented on VirsTimer.Server/virstimer/src/main/kotlin/pl/virstimer/api/SolveController.kt
> +        request.forEach{
użyłbym ".map"

2021-12-05 14:26 UTC, Javorus commented on VirsTimer.Server/virstimer/src/main/kotlin/pl/virstimer/api/SolveController.kt
> +        request.forEach{
dobry pomysł

2021-12-05 15:56 UTC, akmieckowiak approved these changes

2021-12-05 15:56 UTC, merged